// Code generated by MockGen. DO NOT EDIT.
// Source: dbus.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	godbus "github.com/feral-file/godbus"
	gomock "github.com/golang/mock/gomock"
)

// MockDBusClient is a mock of ClientInterface interface.
type MockDBusClient struct {
	ctrl     *gomock.Controller
	recorder *MockDBusClientMockRecorder
}

// MockDBusClientMockRecorder is the mock recorder for MockDBusClient.
type MockDBusClientMockRecorder struct {
	mock *MockDBusClient
}

// NewMockDBusClient creates a new mock instance.
func NewMockDBusClient(ctrl *gomock.Controller) *MockDBusClient {
	mock := &MockDBusClient{ctrl: ctrl}
	mock.recorder = &MockDBusClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBusClient) EXPECT() *MockDBusClientMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockDBusClient) Call(ctx context.Context, name string, path godbus.Path, iface godbus.Interface, method godbus.Member, args ...any) ([]any, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, name, path, iface, method}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Call", varargs...)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Call indicates an expected call of Call.
func (mr *MockDBusClientMockRecorder) Call(ctx, name, path, iface, method interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, name, path, iface, method}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockDBusClient)(nil).Call), varargs...)
}

// Export mocks base method.
func (m *MockDBusClient) Export(obj interface{}, path godbus.Path, iface godbus.Interface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", obj, path, iface)
	ret0, _ := ret[0].(error)
	return ret0
}

// Export indicates an expected call of Export.
func (mr *MockDBusClientMockRecorder) Export(obj, path, iface interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockDBusClient)(nil).Export), obj, path, iface)
}

// OnBusSignal mocks base method.
func (m *MockDBusClient) OnBusSignal(handler godbus.BusSignalHandler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnBusSignal", handler)
}

// OnBusSignal indicates an expected call of OnBusSignal.
func (mr *MockDBusClientMockRecorder) OnBusSignal(handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnBusSignal", reflect.TypeOf((*MockDBusClient)(nil).OnBusSignal), handler)
}

// RemoveBusSignal mocks base method.
func (m *MockDBusClient) RemoveBusSignal(handler godbus.BusSignalHandler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveBusSignal", handler)
}

// RemoveBusSignal indicates an expected call of RemoveBusSignal.
func (mr *MockDBusClientMockRecorder) RemoveBusSignal(handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBusSignal", reflect.TypeOf((*MockDBusClient)(nil).RemoveBusSignal), handler)
}

// RetryableSend mocks base method.
func (m *MockDBusClient) RetryableSend(ctx context.Context, payload godbus.DBusPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryableSend", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryableSend indicates an expected call of RetryableSend.
func (mr *MockDBusClientMockRecorder) RetryableSend(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryableSend", reflect.TypeOf((*MockDBusClient)(nil).RetryableSend), ctx, payload)
}

// Start mocks base method.
func (m *MockDBusClient) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockDBusClientMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockDBusClient)(nil).Start))
}

// Stop mocks base method.
func (m *MockDBusClient) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockDBusClientMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockDBusClient)(nil).Stop))
}
