// Code generated by MockGen. DO NOT EDIT.
// Source: relayer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	relayer "github.com/Feral-File/feralfile-device/components/feral-connectd/relayer"
	gomock "github.com/golang/mock/gomock"
)

// MockRelayerClient is a mock of ClientInterface interface.
type MockRelayerClient struct {
	ctrl     *gomock.Controller
	recorder *MockRelayerClientMockRecorder
}

// MockRelayerClientMockRecorder is the mock recorder for MockRelayerClient.
type MockRelayerClientMockRecorder struct {
	mock *MockRelayerClient
}

// NewMockRelayerClient creates a new mock instance.
func NewMockRelayerClient(ctrl *gomock.Controller) *MockRelayerClient {
	mock := &MockRelayerClient{ctrl: ctrl}
	mock.recorder = &MockRelayerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelayerClient) EXPECT() *MockRelayerClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRelayerClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockRelayerClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRelayerClient)(nil).Close))
}

// Connect mocks base method.
func (m *MockRelayerClient) Connect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockRelayerClientMockRecorder) Connect(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockRelayerClient)(nil).Connect), ctx)
}

// IsConnected mocks base method.
func (m *MockRelayerClient) IsConnected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConnected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConnected indicates an expected call of IsConnected.
func (mr *MockRelayerClientMockRecorder) IsConnected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnected", reflect.TypeOf((*MockRelayerClient)(nil).IsConnected))
}

// OnRelayerMessage mocks base method.
func (m *MockRelayerClient) OnRelayerMessage(handler relayer.Handler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnRelayerMessage", handler)
}

// OnRelayerMessage indicates an expected call of OnRelayerMessage.
func (mr *MockRelayerClientMockRecorder) OnRelayerMessage(handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnRelayerMessage", reflect.TypeOf((*MockRelayerClient)(nil).OnRelayerMessage), handler)
}

// RemoveRelayerMessage mocks base method.
func (m *MockRelayerClient) RemoveRelayerMessage(handler relayer.Handler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveRelayerMessage", handler)
}

// RemoveRelayerMessage indicates an expected call of RemoveRelayerMessage.
func (mr *MockRelayerClientMockRecorder) RemoveRelayerMessage(handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRelayerMessage", reflect.TypeOf((*MockRelayerClient)(nil).RemoveRelayerMessage), handler)
}

// RetryableConnect mocks base method.
func (m *MockRelayerClient) RetryableConnect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryableConnect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryableConnect indicates an expected call of RetryableConnect.
func (mr *MockRelayerClientMockRecorder) RetryableConnect(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryableConnect", reflect.TypeOf((*MockRelayerClient)(nil).RetryableConnect), ctx)
}

// Send mocks base method.
func (m *MockRelayerClient) Send(ctx context.Context, data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockRelayerClientMockRecorder) Send(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockRelayerClient)(nil).Send), ctx, data)
}

// SendNotification mocks base method.
func (m *MockRelayerClient) SendNotification(ctx context.Context, notificationType relayer.NotificationType, message interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotification", ctx, notificationType, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNotification indicates an expected call of SendNotification.
func (mr *MockRelayerClientMockRecorder) SendNotification(ctx, notificationType, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockRelayerClient)(nil).SendNotification), ctx, notificationType, message)
}
