// Code generated by MockGen. DO NOT EDIT.
// Source: systemd.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSystemd is a mock of SystemdInterface interface.
type MockSystemd struct {
	ctrl     *gomock.Controller
	recorder *MockSystemdMockRecorder
}

// MockSystemdMockRecorder is the mock recorder for MockSystemd.
type MockSystemdMockRecorder struct {
	mock *MockSystemd
}

// NewMockSystemd creates a new mock instance.
func NewMockSystemd(ctrl *gomock.Controller) *MockSystemd {
	mock := &MockSystemd{ctrl: ctrl}
	mock.recorder = &MockSystemdMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemd) EXPECT() *MockSystemdMockRecorder {
	return m.recorder
}

// SdNotify mocks base method.
func (m *MockSystemd) SdNotify(unsetEnvironment bool, state string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SdNotify", unsetEnvironment, state)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SdNotify indicates an expected call of SdNotify.
func (mr *MockSystemdMockRecorder) SdNotify(unsetEnvironment, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SdNotify", reflect.TypeOf((*MockSystemd)(nil).SdNotify), unsetEnvironment, state)
}
