// Code generated by MockGen. DO NOT EDIT.
// Source: cpu.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCPUHandler is a mock of HandlerInterface interface.
type MockCPUHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCPUHandlerMockRecorder
}

// MockCPUHandlerMockRecorder is the mock recorder for MockCPUHandler.
type MockCPUHandlerMockRecorder struct {
	mock *MockCPUHandler
}

// NewMockCPUHandler creates a new mock instance.
func NewMockCPUHandler(ctrl *gomock.Controller) *MockCPUHandler {
	mock := &MockCPUHandler{ctrl: ctrl}
	mock.recorder = &MockCPUHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCPUHandler) EXPECT() *MockCPUHandlerMockRecorder {
	return m.recorder
}

// CheckCPUTemperature mocks base method.
func (m *MockCPUHandler) CheckCPUTemperature(ctx context.Context, currentTemp float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckCPUTemperature", ctx, currentTemp)
}

// CheckCPUTemperature indicates an expected call of CheckCPUTemperature.
func (mr *MockCPUHandlerMockRecorder) CheckCPUTemperature(ctx, currentTemp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCPUTemperature", reflect.TypeOf((*MockCPUHandler)(nil).CheckCPUTemperature), ctx, currentTemp)
}
