// Code generated by MockGen. DO NOT EDIT.
// Source: disk.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/Feral-File/feralfile-device/components/feral-watchdog/packages/types"
	gomock "github.com/golang/mock/gomock"
)

// MockDiskHandler is a mock of HandlerInterface interface.
type MockDiskHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDiskHandlerMockRecorder
}

// MockDiskHandlerMockRecorder is the mock recorder for MockDiskHandler.
type MockDiskHandlerMockRecorder struct {
	mock *MockDiskHandler
}

// NewMockDiskHandler creates a new mock instance.
func NewMockDiskHandler(ctrl *gomock.Controller) *MockDiskHandler {
	mock := &MockDiskHandler{ctrl: ctrl}
	mock.recorder = &MockDiskHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiskHandler) EXPECT() *MockDiskHandlerMockRecorder {
	return m.recorder
}

// CheckDiskUsage mocks base method.
func (m *MockDiskHandler) CheckDiskUsage(ctx context.Context, metrics *types.SysMetrics) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckDiskUsage", ctx, metrics)
}

// CheckDiskUsage indicates an expected call of CheckDiskUsage.
func (mr *MockDiskHandlerMockRecorder) CheckDiskUsage(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDiskUsage", reflect.TypeOf((*MockDiskHandler)(nil).CheckDiskUsage), ctx, metrics)
}
