// Code generated by MockGen. DO NOT EDIT.
// Source: commands.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCommandHandler is a mock of HandlerInterface interface.
type MockCommandHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCommandHandlerMockRecorder
}

// MockCommandHandlerMockRecorder is the mock recorder for MockCommandHandler.
type MockCommandHandlerMockRecorder struct {
	mock *MockCommandHandler
}

// NewMockCommandHandler creates a new mock instance.
func NewMockCommandHandler(ctrl *gomock.Controller) *MockCommandHandler {
	mock := &MockCommandHandler{ctrl: ctrl}
	mock.recorder = &MockCommandHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandHandler) EXPECT() *MockCommandHandlerMockRecorder {
	return m.recorder
}

// CleanupPacmanCache mocks base method.
func (m *MockCommandHandler) CleanupPacmanCache(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CleanupPacmanCache", ctx)
}

// CleanupPacmanCache indicates an expected call of CleanupPacmanCache.
func (mr *MockCommandHandlerMockRecorder) CleanupPacmanCache(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupPacmanCache", reflect.TypeOf((*MockCommandHandler)(nil).CleanupPacmanCache), ctx)
}

// RebootSystem mocks base method.
func (m *MockCommandHandler) RebootSystem(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RebootSystem", ctx)
}

// RebootSystem indicates an expected call of RebootSystem.
func (mr *MockCommandHandlerMockRecorder) RebootSystem(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebootSystem", reflect.TypeOf((*MockCommandHandler)(nil).RebootSystem), ctx)
}

// RestartKiosk mocks base method.
func (m *MockCommandHandler) RestartKiosk(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RestartKiosk", ctx)
}

// RestartKiosk indicates an expected call of RestartKiosk.
func (mr *MockCommandHandlerMockRecorder) RestartKiosk(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestartKiosk", reflect.TypeOf((*MockCommandHandler)(nil).RestartKiosk), ctx)
}
