// Code generated by MockGen. DO NOT EDIT.
// Source: systemd_watchdog.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSystemdWatchdog is a mock of WatchdogInterface interface.
type MockSystemdWatchdog struct {
	ctrl     *gomock.Controller
	recorder *MockSystemdWatchdogMockRecorder
}

// MockSystemdWatchdogMockRecorder is the mock recorder for MockSystemdWatchdog.
type MockSystemdWatchdogMockRecorder struct {
	mock *MockSystemdWatchdog
}

// NewMockSystemdWatchdog creates a new mock instance.
func NewMockSystemdWatchdog(ctrl *gomock.Controller) *MockSystemdWatchdog {
	mock := &MockSystemdWatchdog{ctrl: ctrl}
	mock.recorder = &MockSystemdWatchdogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemdWatchdog) EXPECT() *MockSystemdWatchdogMockRecorder {
	return m.recorder
}

// NotifyReady mocks base method.
func (m *MockSystemdWatchdog) NotifyReady() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyReady")
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyReady indicates an expected call of NotifyReady.
func (mr *MockSystemdWatchdogMockRecorder) NotifyReady() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyReady", reflect.TypeOf((*MockSystemdWatchdog)(nil).NotifyReady))
}

// Start mocks base method.
func (m *MockSystemdWatchdog) Start(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx)
}

// Start indicates an expected call of Start.
func (mr *MockSystemdWatchdogMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSystemdWatchdog)(nil).Start), ctx)
}
