// Code generated by MockGen. DO NOT EDIT.
// Source: mediator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/Feral-File/feralfile-device/components/feral-watchdog/packages/types"
	gomock "github.com/golang/mock/gomock"
)

// MockMediator is a mock of MediatorInterface interface.
type MockMediator struct {
	ctrl     *gomock.Controller
	recorder *MockMediatorMockRecorder
}

// MockMediatorMockRecorder is the mock recorder for MockMediator.
type MockMediatorMockRecorder struct {
	mock *MockMediator
}

// NewMockMediator creates a new mock instance.
func NewMockMediator(ctrl *gomock.Controller) *MockMediator {
	mock := &MockMediator{ctrl: ctrl}
	mock.recorder = &MockMediatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediator) EXPECT() *MockMediatorMockRecorder {
	return m.recorder
}

// ProcessMetrics mocks base method.
func (m *MockMediator) ProcessMetrics(ctx context.Context, metrics *types.SysMetrics) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessMetrics", ctx, metrics)
}

// ProcessMetrics indicates an expected call of ProcessMetrics.
func (mr *MockMediatorMockRecorder) ProcessMetrics(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessMetrics", reflect.TypeOf((*MockMediator)(nil).ProcessMetrics), ctx, metrics)
}

// Start mocks base method.
func (m *MockMediator) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockMediatorMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockMediator)(nil).Start))
}

// Stop mocks base method.
func (m *MockMediator) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockMediatorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockMediator)(nil).Stop))
}
