// Code generated by MockGen. DO NOT EDIT.
// Source: ram.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/Feral-File/feralfile-device/components/feral-watchdog/packages/types"
	gomock "github.com/golang/mock/gomock"
)

// MockMemoryHandler is a mock of HandlerInterface interface.
type MockMemoryHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryHandlerMockRecorder
}

// MockMemoryHandlerMockRecorder is the mock recorder for MockMemoryHandler.
type MockMemoryHandlerMockRecorder struct {
	mock *MockMemoryHandler
}

// NewMockMemoryHandler creates a new mock instance.
func NewMockMemoryHandler(ctrl *gomock.Controller) *MockMemoryHandler {
	mock := &MockMemoryHandler{ctrl: ctrl}
	mock.recorder = &MockMemoryHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryHandler) EXPECT() *MockMemoryHandlerMockRecorder {
	return m.recorder
}

// CheckMemoryUsage mocks base method.
func (m *MockMemoryHandler) CheckMemoryUsage(ctx context.Context, metrics *types.SysMetrics) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckMemoryUsage", ctx, metrics)
}

// CheckMemoryUsage indicates an expected call of CheckMemoryUsage.
func (mr *MockMemoryHandlerMockRecorder) CheckMemoryUsage(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMemoryUsage", reflect.TypeOf((*MockMemoryHandler)(nil).CheckMemoryUsage), ctx, metrics)
}
