// Code generated by MockGen. DO NOT EDIT.
// Source: cdp.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCDPClient is a mock of ClientInterface interface.
type MockCDPClient struct {
	ctrl     *gomock.Controller
	recorder *MockCDPClientMockRecorder
}

// MockCDPClientMockRecorder is the mock recorder for MockCDPClient.
type MockCDPClientMockRecorder struct {
	mock *MockCDPClient
}

// NewMockCDPClient creates a new mock instance.
func NewMockCDPClient(ctrl *gomock.Controller) *MockCDPClient {
	mock := &MockCDPClient{ctrl: ctrl}
	mock.recorder = &MockCDPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCDPClient) EXPECT() *MockCDPClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCDPClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockCDPClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCDPClient)(nil).Close))
}

// Init mocks base method.
func (m *MockCDPClient) Init(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockCDPClientMockRecorder) Init(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockCDPClient)(nil).Init), ctx)
}

// Initialized mocks base method.
func (m *MockCDPClient) Initialized() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialized")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Initialized indicates an expected call of Initialized.
func (mr *MockCDPClientMockRecorder) Initialized() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialized", reflect.TypeOf((*MockCDPClient)(nil).Initialized))
}

// IsReconnectionError mocks base method.
func (m *MockCDPClient) IsReconnectionError(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReconnectionError", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReconnectionError indicates an expected call of IsReconnectionError.
func (mr *MockCDPClientMockRecorder) IsReconnectionError(err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReconnectionError", reflect.TypeOf((*MockCDPClient)(nil).IsReconnectionError), err)
}

// Reconnect mocks base method.
func (m *MockCDPClient) Reconnect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconnect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reconnect indicates an expected call of Reconnect.
func (mr *MockCDPClientMockRecorder) Reconnect(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconnect", reflect.TypeOf((*MockCDPClient)(nil).Reconnect), ctx)
}

// Send mocks base method.
func (m *MockCDPClient) Send(method string, params map[string]interface{}) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", method, params)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockCDPClientMockRecorder) Send(method, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockCDPClient)(nil).Send), method, params)
}

// SendCriticalCPUTemperatureNotification mocks base method.
func (m *MockCDPClient) SendCriticalCPUTemperatureNotification(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCriticalCPUTemperatureNotification", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCriticalCPUTemperatureNotification indicates an expected call of SendCriticalCPUTemperatureNotification.
func (mr *MockCDPClientMockRecorder) SendCriticalCPUTemperatureNotification(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCriticalCPUTemperatureNotification", reflect.TypeOf((*MockCDPClient)(nil).SendCriticalCPUTemperatureNotification), ctx)
}
