// Code generated by MockGen. DO NOT EDIT.
// Source: gpu.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGPUHandler is a mock of HandlerInterface interface.
type MockGPUHandler struct {
	ctrl     *gomock.Controller
	recorder *MockGPUHandlerMockRecorder
}

// MockGPUHandlerMockRecorder is the mock recorder for MockGPUHandler.
type MockGPUHandlerMockRecorder struct {
	mock *MockGPUHandler
}

// NewMockGPUHandler creates a new mock instance.
func NewMockGPUHandler(ctrl *gomock.Controller) *MockGPUHandler {
	mock := &MockGPUHandler{ctrl: ctrl}
	mock.recorder = &MockGPUHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGPUHandler) EXPECT() *MockGPUHandlerMockRecorder {
	return m.recorder
}

// GracefulShutdown mocks base method.
func (m *MockGPUHandler) GracefulShutdown(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GracefulShutdown", ctx)
}

// GracefulShutdown indicates an expected call of GracefulShutdown.
func (mr *MockGPUHandlerMockRecorder) GracefulShutdown(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulShutdown", reflect.TypeOf((*MockGPUHandler)(nil).GracefulShutdown), ctx)
}

// HandleGPURecovery mocks base method.
func (m *MockGPUHandler) HandleGPURecovery(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleGPURecovery", ctx)
}

// HandleGPURecovery indicates an expected call of HandleGPURecovery.
func (mr *MockGPUHandlerMockRecorder) HandleGPURecovery(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGPURecovery", reflect.TypeOf((*MockGPUHandler)(nil).HandleGPURecovery), ctx)
}

// ScheduleGPUReboot mocks base method.
func (m *MockGPUHandler) ScheduleGPUReboot(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ScheduleGPUReboot", ctx)
}

// ScheduleGPUReboot indicates an expected call of ScheduleGPUReboot.
func (mr *MockGPUHandlerMockRecorder) ScheduleGPUReboot(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleGPUReboot", reflect.TypeOf((*MockGPUHandler)(nil).ScheduleGPUReboot), ctx)
}
